// Import only the SVGs you actually use
import angular from '../app/assets/svg/skills/angular.svg';
import aws from '../app/assets/svg/skills/aws.svg';
import azure from '../app/assets/svg/skills/azure.svg';
import bootstrap from '../app/assets/svg/skills/bootstrap.svg';
import css from '../app/assets/svg/skills/css.svg';
import django from '../app/assets/svg/skills/django.svg';
import docker from '../app/assets/svg/skills/docker.svg';
import figma from '../app/assets/svg/skills/figma.svg';
import firebase from '../app/assets/svg/skills/firebase.svg';
import flutter from '../app/assets/svg/skills/flutter.svg';
import git from '../app/assets/svg/skills/git.svg';
import html from '../app/assets/svg/skills/html.svg';
import java from '../app/assets/svg/skills/java.svg';
import javascript from '../app/assets/svg/skills/javascript.svg';
import matlab from '../app/assets/svg/skills/matlab.svg';
import microsoftoffice from '../app/assets/svg/skills/microsoftoffice.svg';
import mongoDB from '../app/assets/svg/skills/mongoDB.svg';
import mysql from '../app/assets/svg/skills/mysql.svg';
import nextJS from '../app/assets/svg/skills/nextJS.svg';
import numpy from '../app/assets/svg/skills/numpy.svg';
import python from '../app/assets/svg/skills/python.svg';
import pytorch from '../app/assets/svg/skills/pytorch.svg';
import react from '../app/assets/svg/skills/react.svg';
import selenium from '../app/assets/svg/skills/selenium.svg';
import sketch from '../app/assets/svg/skills/sketch.svg';
import tailwind from '../app/assets/svg/skills/tailwind.svg';
import tensorflow from '../app/assets/svg/skills/tensorflow.svg';
import wordpress from '../app/assets/svg/skills/wordpress.svg';
import pandas from '../app/assets/svg/skills/pandas.svg';
import scikitlearn from '../app/assets/svg/skills/scikit-learn.svg';
import fastapi from '../app/assets/svg/skills/fastapi.svg';

export const skillsImage = (skill) => {
  const skillID = skill.toLowerCase();
  switch (skillID) {
    case 'angular': return angular;
    case 'aws': return aws;
    case 'azure': return azure;
    case 'bootstrap': return bootstrap;
    case 'css': return css;
    case 'django': return django;
    case 'docker': return docker;
    case 'figma': return figma;
    case 'firebase': return firebase;
    case 'flutter': return flutter;
    case 'git': return git;
    case 'html': return html;
    case 'java': return java;
    case 'javascript': return javascript;
    case 'matlab': return matlab;
    case 'microsoft office': return microsoftoffice;
    case 'mongodb': return mongoDB;
    case 'mysql': return mysql;
    case 'next js': return nextJS;
    case 'numpy': return numpy;
    case 'python': return python;
    case 'pytorch': return pytorch;
    case 'react': return react;
    case 'selenium': return selenium;
    case 'sketch': return sketch;
    case 'tailwind': return tailwind;
    case 'tensorflow': return tensorflow;
    case 'wordpress': return wordpress;
    case 'pandas': return pandas;
    case 'scikit-learn': return scikitlearn;
    case 'fastapi': return fastapi;
    default: return null;
  }
};
